# serverless.yml
service: serverless-example

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  
functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello
          method: get
          cors: true

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true

  readUsers:
    handler: handler.readUsers
    events:
      - http:
          path: users
          method: get
          cors: true

  readUserById:
    handler: handler.readUserById
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
  
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: patch
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
